version: '3'
services:
  video-streaming:
    image: video-streaming
    build: 
      context: ./Web
      dockerfile: Dockerfile
    container_name: video-streaming
    ports:
      - "3000:3000"
    
    environment:
      - PORT=3000

    restart: "no"